### ISSUE TITLE
use closure insted of inline functions

### ISSUE THREAD

**Issue by gabrielreisn** [UsefulHunter/first-todo-challenge#1]
inline functions cause re-render independent of props/state change. You should avoid it
https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-closure-b2f0d2152b36

ping me if you need help on this one

https://github.com/UsefulHunter/first-todo-challenge/blob/master/src/components/Option.js#L10

**Comment by UsefulHunter** [comment]
https://github.com/UsefulHunter/first-todo-challenge/commit/6930c2e8853a777810ee5cb74a0899ccfa8791c3
I referenced this issue in the commit above, and learned that this really makes a diference on the number of re-renderings of the application.

**Comment by gabrielreisn** [comment]
:100:
